### PR TITLE
Fix racy broken WorkerStressTests.

### LINKED ISSUE #878: WorkerStressTest seems to be broken
Running `./gradlew build` locally will hang at `WorkerStressTest`.

I suspect this might be why all our PRs in the last few days have been timing out as well.

I noticed this first on my Kotlin 1.3.70-eap branch, and assumed it had something to do with the new version, but this is happening on master. The only coroutines-related thing that I can think of that changed recently was making workers launch on the `Unconfined` dispatcher, but that PR went green.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
Fixes #878.

### CODE REVIEW

File: kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt [hunk 1]
```diff
@@ -29,31 +31,36 @@ class WorkerStressTest {
...
+      val outputs = launchWorkflowIn(this, workflow, flowOf(Unit)) {
+        // Collect to a channel immediately so that we don't miss any outputs.
+        it.outputs.produceIn(this)
+      }
 
       // This should just work, and the test will finish, but this is broken by
       // https://github.com/Kotlin/kotlinx.coroutines/issues/1584 and will crash instead if
       // receiveOrClosed is used.
       channel.close()
-      delay(1)
```
Comment (zach-klippenstein) [inline kotlin/workflow-testing/src/test/java/com/squareup/workflow/WorkerStressTest.kt]: Not sure why this delay was ever here. This test should never have passed.
