### PR TITLE
Fixes BackStackContainer config change.

### LINKED ISSUE #400: BackstackContainer view state lost on config change
* Launch Tic Tac Toe sample
 * foo@2fa / password
 * rotate
 * go back

Transition is a push. Should be a pop. Indicates that viewStateCache was not saved

### PR DESCRIPTION
**Pull request by rjrjr**
Closes #400.

Our view persistence story got a lot simpler with the move to  `LayoutRunner`,
since we no longer try to render views before they have a complete rendering
to display. `BackStackContainer` didn't get the memo, and its assumption
that `onRestoreInstanceState` would come too late was breaking things.

Fix is simple, don't go like that.

### CODE REVIEW

File: kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt [hunk 1]
```diff
@@ -54,8 +53,7 @@ open class BackStackContainer(
 ) : FrameLayout(context, attributeSet), HandlesBack {
   constructor(context: Context) : this(context, null)
 
-  private var restored: ViewStateCache? = null
-  private val viewStateCache by lazy { restored ?: ViewStateCache() }
+  private val viewStateCache = ViewStateCache()
```
Comment (zach-klippenstein) [inline kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt]: 😍

**Comment by rjrjr** [comment]
Still no unit / integration tests for this. I dug into that a bit and all the options still suck, so I'd prefer not to block the fix. Tracked at #401

File: kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt [hunk 2]
```diff
@@ -134,14 +132,13 @@ open class BackStackContainer(
   }
 
   override fun onSaveInstanceState(): Parcelable {
-    showing?.let { viewStateCache.save(it) }
```
Comment (rjrjr) [inline kotlin/workflow-ui-android/src/main/java/com/squareup/workflow/ui/backstack/BackStackContainer.kt]: No longer need the `save()` call, b/c Android built-in call is no longer busted.
