### PR TITLE
Handle `Actions` from a sink synchronously.

### LINKED ISSUE #348: Swift workflow loop updates asynchronously, can cause lost events
tl;dr: Handling an action and having a render pass occur yields the main loop, which can cause UI events to be missed, as the previous sink will be invalid, and the updated sink won't be set on the UI side.

Longer form example that shows the behavior:
```swift
// The state of the text field is managed in the workflow. Updates to it when edited are sent back via the `.didChange` closure.
struct ExampleScreen: Screen {
  var text: String
  var didChange: (String) -> Void
}

final class ExampleViewController /*...*/ {
  let textField: UITextField

  /* snipped */

    override func viewDidLoad() {
        super.viewDidLoad()

        // Any time the text changes, send the event back to the workflow
        textField.addTarget(
            self,
            action: #selector(textDidChange(sender:)),
            for: .editingChanged)

        // rest of viewDidLoad
    }

    @objc private func textDidChange(sender: UITextField) {
        guard let text = sender.text else { return }
        screen.onTextChanged(text)
    }

    override func screenDidChange(from previousScreen: PlaceholderScreen) {
        // Update the text field state based on the state from the workflow.
        textField.text = screen.text
    }
}
```

Relevant parts of workflow implementation:
```swift
// MARK: Actions

extension RootWorkflow {

    enum Action: WorkflowAction {

        typealias WorkflowType = RootWorkflow

        case updated(String)

        func apply(toState state: inout RootWorkflow.State) -> RootWorkflow.Output? {

            switch self {
            case .updated(let text):
                state.text = text
            }
            return nil
        }

    }
}


// MARK: Rendering

extension RootWorkflow {

    public typealias Rendering = ExampleScreen

    public func render(state: State, context: RenderContext<RootWorkflow>) -> Rendering {
        let sink = context.makeSink(of: Action.self)

        return PlaceholderScreen(
            text: state.text,
            onTextChanged: { text in
                sink.send(.updated(text))
            })
    }
}
```
Explanation of what's happening:
The text field's `textDidChange` action occurs, and the current text value is sent back to the workflow with a `sink.send(.updated(text))` call.

The `apply` method is called, and the workflow's state is updated with the updated text. The next render pass occurs, and the value of `state.text` is apply back to the UITextField.

Because the text input is happening rapidly, UIKit will send the next event to through the text field as soon as the main thread is available. This is easiest to reproduce synthetically with a KIF test, but using a hardware keyboard *can* produce this behavior (just less consistently).

Since the Signal backing the sink is no longer valid after a first action has been received (and it doesn't, nor shouldn't, batch the events), when the second time `sink.send(.updated(text))` is called, the action is dropped.

The text field's state now includes two keypresses (ie: "ab"), but the workflow has only gotten an updated text for the first (ie: "a"). When the render pass completes, the text field (being applied from the screen) will have `textField.text` be "a", and we've lost an entered character.

The most likely path forward for this is to ensure that it is synchronous for the next render pass to occur directly after handling an action (ie: use the UIScheduler in the `SubtreeManager`). This does *not* prevent this in the case where the UI update based on a new screen is happening asynchronously (deferred applying of the updated closure) - so there still could be cases where the UI implementation can cause dropped events.

### PR DESCRIPTION
**Pull request by davidapgar**
This guarantees that an action being applied from a sink
will immediately cause a render pass, providing a new sink to
the UI side, and prevents lost events.

Additionally, fixes that the SignalProducer from a worker
was not being cancelled on a subsequent render pass if it
was not declared.

Fixes #348

### CODE REVIEW

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 1]
```diff
@@ -230,15 +290,16 @@ extension WorkflowNode.SubtreeManager {
...
 
         init(worker: W, outputMap: @escaping (W.Output) -> AnyWorkflowAction<WorkflowType>) {
             self.worker = worker
             self.signalProducer = worker.run()
             self.outputMap = outputMap
             super.init()
 
-            disposable = signalProducer
+            signalProducer
+                .take(during: lifetime)
```
Comment (davidapgar) [inline swift/Workflow/Sources/SubtreeManager.swift]: This change has a worker get cancelled if it's not still declared on a subsequent render pass. See the test in `SubtreeManagerTests` for it.

(Alternatively, this could have been done by holding onto the `disposable`, and calling `disposable?.dispose()` in `deinit()`. I'm open to either approach if someone has strong feelings)

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 2]
```diff
@@ -9,29 +9,28 @@ extension WorkflowNode {
...
 
+        /// The current array of workers
         private (set) internal var childWorkers: [AnyChildWorker] = []
 
-        private let (lifetime, token) = Lifetime.make()
+        /// Subscriptions from the outside world.
+        private var subscriptionContext: SubscriptionContext = SubscriptionContext(eventSources: [])
 
-        init() {
-            childEvent
```
Comment (davidapgar) [inline swift/Workflow/Sources/SubtreeManager.swift]: This logic is moved into the `SubscriptionContext`. After the sink changes, it was the only thing still using this (since `Workers` and `Workflows` call the handler function). Mostly refactored to keep it consistent.

File: swift/WorkflowTesting/Sources/WorkflowRenderTester.swift [hunk 3]
```diff
@@ -151,6 +151,15 @@ fileprivate final class RenderTestContext<T: Workflow>: RenderContextType {
         return workflow.render(state: testContext.state, context: context)
     }
 
+    func makeSink<Action>(of actionType: Action.Type) -> Sink<Action> where Action : WorkflowAction, T == Action.WorkflowType {
+        let (signal, observer) = Signal<AnyWorkflowAction<WorkflowType>, NoError>.pipe()
```
Comment (davidapgar) [inline swift/WorkflowTesting/Sources/WorkflowRenderTester.swift]: For the render tester, it's the same implementation as before `makeSink` was a real function. However, all of this is synchronous in the tester, so it will behave appropriately.

I want to revisit the tester after this change anyway, since this should allow us expect/assert specific concrete Action types (which couldn't be done before, since they were wrapped in the type erasure `AnyWorkflowAction`). But will likely be a followup.

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 4]
```diff
@@ -190,6 +210,46 @@ extension WorkflowNode.SubtreeManager {
...
+            case valid(handler: (Output) -> Void)
+            case invalid
+        }
+
+        init() {
+            self.validationState = .preparing
+        }
+
+        func handle(action: AnyWorkflowAction<WorkflowType>) {
+            switch validationState {
```
Comment (davidapgar) [inline swift/Workflow/Sources/SubtreeManager.swift]: This covers the *majority* of pre-use/after-use cases. There is still a gap of `sink.send` being call immediately after `render` completes (ie: in `screenDidChange`). It *does* fail, since the `Property` backing the rendering asserts that it's been re-entrantly updated, but it's a less than ideal failure message.

I'm open to thoughts on this. From the best of my exploration, it would have to be in `WorkflowHost` *after* updating the `rendering` property telling the `WorkflowNode` "you're ready", which seems like a clumsy API.

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 5]
```diff
@@ -190,6 +210,46 @@ extension WorkflowNode.SubtreeManager {
 
 }
 
+
+extension WorkflowNode.SubtreeManager {
+    fileprivate final class SinkContext {
```
Comment (timdonnelly) [inline swift/Workflow/Sources/SubtreeManager.swift]: We use the `context` term in a bunch of places, I hope we can find a more descriptive word here. No brilliant suggestions from me at the moment, however.

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 6]
```diff
@@ -49,8 +48,16 @@ extension WorkflowNode {
             /// as a result of this call to `render`.
             self.childWorkflows = context.usedChildWorkflows
             self.childWorkers = context.usedChildWorkers
+            self.sinks = context.sinks
 
-            /// Finally, merge all of the events together from the new set of children and start listening to them
+            /// Enable and start listening to events from sinks, child workflows, and workers.
+            for sink in self.sinks {
```
Comment (timdonnelly) [inline swift/Workflow/Sources/SubtreeManager.swift]: As far as I'm aware, `Sink`s are explicitly for use in UI. As such, their events should always come in on the main thread.

We should assert using

```
dispatchPrecondition(condition: .onQueue(.main))
```

either here or somewhere in the sink plumbing.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (timdonnelly) [reply swift/Workflow/Sources/SubtreeManager.swift]: I actually don't think that's a bad idea at all.

When a tree update happens, renderings flow (down|up) to the root. So from the root we end up calling `render()`:

https://github.com/square/workflow/blob/02a87fc6c4507f7c007f5de0d95fa125c796e32e/swift/Workflow/Sources/WorkflowHost.swift#L56

We can immediately call `didRender()` after the render pass, which can propagate through the entire tree. Each node can then activate its event sinks as needed.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 6 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: `Sink`s *currently* are only used for UI events. I agree with adding a precondition on these, but want to leave open option of running the entirety of a workflow on a background thread (ie: not bound to a container/UI, just from a `WorkflowHost`).

I'll go with adding it for now, and then if/when we want background support, make the appropriate changes.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 5 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: +1. It's a bad name for this (since we already have a bunch of other things with this name). I'll come up with another one.

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 7]
```diff
@@ -9,29 +9,28 @@ extension WorkflowNode {
...
-                }
-        }
+        init() {}
 
         /// Performs an update pass using the given closure.
         func render<Rendering>(_ actions: (RenderContext<WorkflowType>) -> Rendering) -> Rendering {
 
+            /// Invalidate the previous sinks.
+            for sink in sinks {
+                sink.invalidate()
```
Comment (zach-klippenstein) [inline swift/Workflow/Sources/SubtreeManager.swift]: What does invalidating a sink do?

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: That sounds very similar to the way it works in Kotlin. Each iteration of the main loop consists of three(-ish) phases:
1. **Render pass** (non-blocking) – constructs the context for the current iteration, subscribes channels to every new signal/event sink, tears down obsolete ones.
    1.5. **Snapshot** (non-blocking, separate pass than rendering but happens immediately after) – constructs snapshot of the current state tree.
2. **Publish** (possibly blocking if backpressure) – send rendering, snapshot, and optionally the last output to the consumer of the workflow runtime.
3. **"Tick"** (usually blocking, bad name) – selects on all channels and waits for the next "thing" to happen. Only allows one atomic "thing" to happen at once, runs all `WorkflowAction`s all the way up the tree, and returns the root workflow's optional `OutputT` for that iteration (which is then emitted in the subsequent iteration's "Publish" pass).

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 7 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Just sets its internal state to "invalid". `sink` in this scope is the (poorly named currently) `SinkContext` that is actually wired into the subtree manager.

If it receives an event when it's in the `invalid` state, it will assert (fail fast) instead of silently dropping it.

Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: Ah, ok, so this is basically the equivalent of this line in a PR i've got open:

https://github.com/square/workflow/blob/798afacb46481a8998deff2c3b47784609fd0de4/kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/WorkflowNode.kt#L125

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: That's good insight, and gives me confidence this is an appropriate extra step to add.

The behavior will/should be (the differentiation is the most of this will by synchronous):
**Render pass**
1) **Prepare** (what you listed as render pass): Construct the context and call `render` on the workflow.
  - Invalidate old sinks, remove obsolete subscriptions, child workflows, workers (that are no longer declared).
  - Gather all the sinks, subscriptions, etc from render, in a "pending" state.
2) **Publish** (still synchronous) - Send the rendering and optional output.
3) **Enable** (synchronous as well) - Enable all of the sinks, subscriptions, workers, etc. The subscriptions and workers are explicitly subscribed on a queue that guarantees that they will not emit synchronously, so for them having a separate "enable" isn't technically necessary, but fits the model nicely. This will walk the tree of workflows again to enable the root and all the children/grandchildren in a synchronous pass.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 7 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Yup! I assume that `cancel` in that context will make it assert if it's still used?

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 6 above)
Comment (rjrjr) [reply swift/Workflow/Sources/SubtreeManager.swift]: Rather than hard coding main, can you make the queue configurable, with .main as a default value?

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (rjrjr) [reply swift/Workflow/Sources/SubtreeManager.swift]: hyper meta nit: even though these are "internal" concerns, it'd be cool if we used the same naming for these passes in both code bases. That would let us better describe the contract in shared docs.

How does this sound: Dave comes up with good names in this PR, and Kotlin catches up once that mini-bikeshed settles.

Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: The names don't exist in code. "render" is the same in both already I think, and that's really the only part they share.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 1 above)
Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: In Rx, we tend to use the latter pattern if we need to re-subscribe later. We add disposables to a `CompositeDisposable` and clear it if it's a one-shot thing.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 7 above)
Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: Yep.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: I'm debating where the best place to document this is. I feel like at least initially I'm going to write up this behavior as doc comments in the code (so that it's accurate). Overall, I have been kicking around the idea of writing (ie: have started and stopped a few times) a "implementation" or "lifecycle" or "internals" doc that codifies all of these details.

Also debated adding an "RFC" section to the docs, specifically talking about issues like this (so they're more discoverable than just github issues), but don't have a strong preference yet.

Comment (rjrjr) [reply swift/Workflow/Sources/SubtreeManager.swift]: I actually think this would be good method documentation for render(). render is the most central method in the library, and this describes the precise contract of when the method is called, what it builds, and what is allowed to happen to the thing that it builds.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 6 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: That's likely the long term path for this (making the queue configurable). Since we are only using this on the main queue currently, I'm going to leave it as is for the moment (and do that in a followup).

https://github.com/square/workflow/issues/364

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (zach-klippenstein) [reply swift/Workflow/Sources/SubtreeManager.swift]: > I have been kicking around the idea of writing (ie: have started and stopped a few times) a "implementation" or "lifecycle" or "internals" doc that codifies all of these details.

I had a section in the docs rewrite outline for this, but Ray suggested using it for something else: https://docs.google.com/document/d/1hlJZh72ZQ-Abd9XZRm4MjsULWQE2pCDTHy-WrFA_XiE/edit#heading=h.4l7zcgaeyx6f

Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Updated, adding an `enableRendering` method that must be called before any actions are valid to be handled.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 5 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Ended up with `ActionPipe` as it's the pipe on the sink that actions flow down.

I'm still not 100% happy with it, but it's at least not a collision with "context".

`ActionDrain`? `ActionHandler`?

Comment (timdonnelly) [reply swift/Workflow/Sources/SubtreeManager.swift]: 😂 I almost suggested pipe.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 6 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Added verification we are on the `DispatchQueue.workflowExectution` for all actions that come in (covering UI events, as well as asserting that's what we subscribe on for workers and subscriptions)

Comment (timdonnelly) [reply swift/Workflow/Sources/SubtreeManager.swift]: We actually have the workflow queue defined in an extension somewhere, you'd want to assert that you're on that queue versus main (the current definition just resolves to main).

File: swift/Workflow/Sources/SubtreeManager.swift [hunk 8]
```diff
@@ -49,30 +48,32 @@ extension WorkflowNode {
...
 
-            for worker in self.childWorkers {
-                worker.onUpdate = { [weak self] output in
+            /// Return the rendered result
+            return rendering
+        }
+
+        /// Enable the actionPipes for the previous rendering. The actionPipes are not valid until this has
+        /// be called. If is an error to call this twice without generating a new rendering.
+        func enableRendering() {
```
Comment (davidapgar) [inline swift/Workflow/Sources/SubtreeManager.swift]: This is now the second pass on a render loop. All event sources go through the `ActionPipe`s, so it's a singular path that is synchronous to validate we are on the correct dispatch queue, as well as having been enabled.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 6 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Yup, that's the one I used.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 4 above)
Comment (timdonnelly) [reply swift/Workflow/Sources/SubtreeManager.swift]: supernit: not a fan of `enableRendering` – it doesn't actually *do* anything to the rendering. We're really enabling any captured event sinks.

You could either name it based on what it does: `enableEvents()`, etc.

or name it based on the phase in the render cycle

`didEmitRendering()`

Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: Updated to `enableEvents` - you are right, that's a much better name.

File: swift/Workflow/Sources/SubtreeManager.swift (hunk 1 above)
Comment (davidapgar) [reply swift/Workflow/Sources/SubtreeManager.swift]: I think this feels appropriate for ReactiveSwift, and the lifetimes (if it was RxSwift, there would be a "disposeBag" (neat name) that would also get rid of these as the disposable when the object gets deallocated).  Since we are never unsubscribing from these except with the object goes away, I'm not going to add the extra code to get rid of it in `deinit`

File: swift/Workflow/Sources/WorkflowNode.swift [hunk 9]
```diff
@@ -2,7 +2,7 @@ import ReactiveSwift
 import Result
 
 /// Manages a running workflow.
-final class WorkflowNode<WorkflowType: Workflow> {
+final internal class WorkflowNode<WorkflowType: Workflow> {
```
Comment (timdonnelly) [inline swift/Workflow/Sources/WorkflowNode.swift]: `internal` is implicit, generally prefer leaving it out (or, for consistency, add it everywhere... but that doesn't sound great)

Comment (davidapgar) [reply swift/Workflow/Sources/WorkflowNode.swift]: Took it back off. It was mostly that I was walking through all these types, it was a helpful signal to me of what is and isn't visible.

I agree with this overall (leaving it off, since it is implicit. Adding it everywhere does seem like it too much noise)

File: swift/Workflow/Sources/WorkflowHost.swift [hunk 10]
```diff
@@ -59,6 +60,8 @@ public final class WorkflowHost<WorkflowType: Workflow> {
             outputEventObserver.send(value: outputEvent)
         }
 
+        rootNode.enableEvents()
```
Comment (timdonnelly) [inline swift/Workflow/Sources/WorkflowHost.swift]: It seems like this will get a bit complicated in the case where a rendering causes an event. This call to `enableEvents` will causes something down in the tree to dequeue its pending event, which will bubble up and recursively call `self.handle(output:)`.

That seems like it will (at the very least) result in out of order debug info (the recursive invocation will call `debugger?.didUpdate` before the outer one)

Comment (timdonnelly) [reply swift/Workflow/Sources/WorkflowHost.swift]: I don't have all of this architecture in my head, but it might be nice if `enableEvents` could optionally return a `WorkflowNode<WorkflowType>.Output` value, then you could predictable handle the update inline here.

Comment (davidapgar) [reply swift/Workflow/Sources/WorkflowHost.swift]: Yes - I agree that we need to handle the debug info appropriately (so it's in the "correct" order of what happened).

I *think* reordering in `WorkflowHost` to emit the debug event before calling `enableEvents` will have the correct sequence. Basically, `enableEvents` needs to be the last thing in `handle` called, so that it is properly "tail recursive" to guarantee the right order. I'll add a test case around this, to ensure whatever is done behave correctly.

Comment (davidapgar) [reply swift/Workflow/Sources/WorkflowHost.swift]: Updated `WorkflowHost` and added a test for this. By having `enableEvents` be the last thing called in `handle` it's now ensured that the debug info comes through in the correct order.

**Comment by RoyalPineapple** [comment]
LGTM

**Comment by davidapgar** [comment]
@timdonnelly All updated. This now covers all the cases (including events happening between `render` being called, and `enableEvents`), as well as ensuring the debug info is in order.

Validated against all of our internal code using this - please take a look, I'd like to get this landed so we can update.
