### PR TITLE
Fix the TracingDiagnosticListenerTest.golden value test.

### LINKED ISSUE #664: `TracingDiagnosticListenerTest.golden value` is brittle
It has GC events in its expected output.

```
org.junit.ComparisonFailure: expected:<...filing"}},
{"name":"[GC detected","cat":"system","ph":"i","ts":0,"pid":0,"tid":0,"s":"g","args":{"freeMemory":42,"totalMemory":43}},
{"name":"used/free memory","ph":"C","ts":0,"pid":0,"tid":0,"args":{"usedMemory":1,"freeMemory":42}},
{"name":"]TestWorkflow (0)","c...> but was:<...filing"}},
{"name":"[]TestWorkflow (0)","c...>
```

_Originally posted by @rjrjr in https://github.com/square/workflow/pull/657#issuecomment-541164965_

### PR DESCRIPTION
**Pull request by zach-klippenstein**
This test was not injecting the `GcDetector`, so it was only passing because
garbage collections happened to be getting detected consistently on most test runs.

This change injects the detector and changes the test to expiclitly trigger it.

Fixes #664.

### CODE REVIEW

File: kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListener.kt [hunk 1]
```diff
@@ -72,31 +72,53 @@ fun TracingDiagnosticListener(
...
  * visiting `chrome://tracing`.
- *
- * @param loggerProvider A function that returns a [TraceLogger] that will be used to write trace
- * events. The function gets the [CoroutineScope] that the workflow runtime is running in, as well
- * as the same workflow type description passed to [WorkflowDiagnosticListener.onWorkflowStarted].
  */
 @UseExperimental(VeryExperimentalWorkflow::class)
-class TracingDiagnosticListener(
-  private val memoryStats: MemoryStats = RuntimeMemoryStats,
+class TracingDiagnosticListener internal constructor(
```
Comment (rjrjr) [inline kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListener.kt]: Wouldn't hurt to put a comment on the internal constructor explaining that it's broken out s.t. we can unit test w/mocked gc collector.

Comment (zach-klippenstein) [reply kotlin/workflow-tracing/src/main/java/com/squareup/workflow/diagnostic/tracing/TracingDiagnosticListener.kt]: Done.
