### PR TITLE
Fixes StatelessWorkflow.action.

### LINKED ISSUE #860: StatelessWorkflow.action doesn't, like, work
StatelessWorkflow.render provides a `RenderContext<Nothing, ResultT>`. The `action` extension creates `WorkflowAction<Unit, ResultT>`.

### PR DESCRIPTION
**Pull request by rjrjr**
And uses it in the dungeon sample. Closes #860.

### CODE REVIEW

File: kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/TimeMachineAppWorkflow.kt [hunk 1]
```diff
@@ -40,10 +39,7 @@ class TimeMachineAppWorkflow(
 ) : StatelessWorkflow<BoardPath, Nothing, ShakeableTimeMachineRendering>() {
 
   private val timeMachineWorkflow =
-    ShakeableTimeMachineWorkflow<Props, Nothing, AlertContainerScreen<Any>>(
-        TimeMachineWorkflow(appWorkflow, clock),
-        context
-    )
+    ShakeableTimeMachineWorkflow(TimeMachineWorkflow(appWorkflow, clock), context)
```
Comment (zach-klippenstein) [inline kotlin/samples/dungeon/app/src/main/java/com/squareup/sample/dungeon/TimeMachineAppWorkflow.kt]: Yikes, thank you 😅

File: kotlin/samples/dungeon/timemachine/src/main/java/com/squareup/sample/timemachine/TimeMachineWorkflow.kt [hunk 2]
```diff
@@ -99,9 +98,5 @@ class TimeMachineWorkflow<P, O : Any, out R>(
     return context.renderChild(recordingWorkflow, recorderProps)
   }
 
-  private fun forwardOutput(output: O) = object : WorkflowAction<Nothing, O> {
-    override fun Updater<Nothing, O>.apply() {
-      setOutput(output)
-    }
-  }
+  private fun forwardOutput(output: O) = action { setOutput(output) }
```
Comment (zach-klippenstein) [inline kotlin/samples/dungeon/timemachine/src/main/java/com/squareup/sample/timemachine/TimeMachineWorkflow.kt]: 😍
