### PR TITLE
Make it possible to pass just the snapshot for the root workflow into the test methods.

### LINKED ISSUE #538: testFromStart with SnapShot fails tests
I’m upgrading our OnlineBookingWorkflow to v2. In our tests we’re using 
```
workflow.testFromStart(snapshot)

{ ... }
```
It looks like we’re the first people to be using this method with a snapshot and we’re having some issues. We’re getting EOFExceptions (end of file) when we try to read from our snapshot.

It looks like when we call `testFromStart` we create a `WorkflowNode`, which has a `state` as an instance variable. If the snapshot is supplied then it will try to restore the state during initialization. When it restores the state it appears that it expects the buffer to be formatted as so
`[length of parent snapshot][parent snapshot][length of child snapshot][child snapshot]`
But the snapshot that we pass in is only the `[parent snapshot]`. So when we try to collect the [parent snapshot] to parse into a state it crashes since the first 4 bytes in the buffer are `com.`, which is a huge int and tries to read too much. lmk if that makes sense.

The consumers of the method probably shouldn’t be adding those bytes. It seems like `testFromStart` should prepend the length of the snapshot.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
This PR gives you the option of starting a workflow test session with either just the snapshot for the root workflow itself, or the complete snapshot of the entire tree from a previous workflow run.

Fixes #538.

### CODE REVIEW

File: kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    writeByteStringWithLength(childId.toByteString())
+    writeByteStringWithLength(childSnapshot.bytes)
+  }
+}
+
+/**
+ * Parses a "root" snapshot and the list of child snapshots with associated [WorkflowId]s from a
+ * [ByteString] returned by [createTreeSnapshot].
+ *
+ * Never returns an empty root snapshot: if the root snapshot is empty it will be null.
```
Comment (rjrjr) [inline kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt]: What about child snapshots? Might they be empty?

Comment (rjrjr) [reply kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt]: Looks like no. Why the difference?

File: kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+ *
+ * @see createTreeSnapshot
+ */
+internal fun parseTreeSnapshot(
+  treeSnapshot: ByteString
```
Comment (rjrjr) [inline kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt]: Nit, your call: be a bit less confusing in here if the `ByteString`s had some other name. e.g. `rootBytes` or `rootSnapshotBytes`.

File: kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt [hunk 3]
```diff
@@ -59,9 +58,30 @@ data class WorkflowTestParams<out StateT>(
...
-     * snapshot.
+     * snapshot.  Only applies to [StatefulWorkflow][com.squareup.workflow.StatelessWorkflow]s.
+     *
+     * This differs from [StartFromCompleteSnapshot] because it represents only the snapshot for
+     * the root workflow, without any of the snapshots of its children or other bookkeeping data
+     * added by the workflow runtime.
+     *
+     * @param snapshot A [Snapshot] that can be directly parsed by a workflow's `initialState`
+     * method. For workflow trees, this is only the snapshot of the _root_ workflow. Testing with
+     * a complete snapshot of a workflow tree is not currently supported.
```
Comment (rjrjr) [inline kotlin/workflow-runtime/src/main/java/com/squareup/workflow/testing/WorkflowTestParams.kt]: Maybe say explicitly that this is the snapshot returned by the root's `StatefulWorkflow.snapshotState`, for easier contrast with the `WorkflowTester.awaitNextSnapshot` bit below.

File: kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt (hunk 1 above)
Comment (zach-klippenstein) [reply kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt]: Because the current node doesn't actually care if its children have snapshots or not.

Comment (zach-klippenstein) [reply kotlin/workflow-runtime/src/main/java/com/squareup/workflow/internal/TreeSnapshots.kt]: Added some documentation about this.

**Comment by zach-klippenstein** [comment]
Pardon the noise there, merge-when-green bot did a bunch of weird stuff that I had to clean up. This should be good to merge on green now.
